2019-05-18 11:55:31,168 INFO: Microblog startup [in /home/mohtadi/Projects/microblog/app/__init__.py:47]
2019-05-18 11:57:33,778 INFO: Microblog startup [in /home/mohtadi/Projects/microblog/app/__init__.py:47]
2019-05-18 11:57:41,366 ERROR: Exception on /edit_profile [POST] [in /home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py:1761]
Traceback (most recent call last):
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/mohtadi/Projects/microblog/app/routes.py", line 19, in edit_profile
    return redirect(url_for('user(current_user.username)'))
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/home/mohtadi/anaconda3/lib/python3.7/site-packages/werkzeug/routing.py", line 1776, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user(current_user.username)'. Did you mean 'register' instead?
2019-05-18 12:00:14,437 INFO: Microblog startup [in /home/mohtadi/Projects/microblog/app/__init__.py:47]
